name: gimp
version: '2.8.22'
summary: GNU Image Manipulation Program
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist,
  GIMP provides you with sophisticated tools to get your job done. You can
  further enhance your productivity with GIMP thanks to many customization
  options and 3rd party plugins.

confinement: strict
icon: gimp.png

apps:
  gimp:
    command: desktop-launch $SNAP/usr/bin/gimp
    desktop: usr/share/applications/gimp.desktop
    environment:
      GIMP2_DATADIR: $SNAP/usr/share/gimp/2.0
      GIMP2_LOCALEDIR: $SNAP/usr/share/gimp/2.0/locale
      GIMP2_PLUGINDIR: $SNAP/usr/lib/gimp/2.0
      GIMP2_SYSCONFDIR: $SNAP/etc/gimp/2.0
      GEGL_PATH: $SNAP/usr/lib/gegl-0.2
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - opengl
    - removable-media
    - wayland
    - x11

parts:
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-plugins:
    after: [alsa-lib]

  gegl:
    plugin: autotools
    source: git://git.gnome.org/gegl
    source-tag: 'GEGL_0_2_0'
    configflags:
    - 'LDFLAGS=-lm'
    - '--prefix=/usr'
    build-packages:
    - gettext
    - intltool
    # - libavformat-dev # not compatible - need earlier release
    - libbabl-dev
    - libc6-dev
    - libcairo2-dev
    - libexiv2-dev
    - libgdk-pixbuf2.0-dev
    - libglib2.0-dev
    - libgraphviz-dev
    - libjasper-dev
    - libjpeg8-dev
    - libopenexr-dev
    - libopenraw-dev
    - libpango1.0-dev
    - libpangocairo-1.0-0
    - libpng12-dev
    - librsvg2-dev
    - libsdl2-dev
    - libspiro-dev
    - libv4l-dev
    - valac
    stage-packages:
    # - libavformat-ffmpeg56 # not compatible - need earlier release
    - libbabl-0.1-0
    - libcairo2
    - libcdt5
    - libcgraph6
    - libexiv2-14
    - libgdk-pixbuf2.0-0
    - libglib2.0-0
    - libgvc6
    - libgvc6-plugins-gtk
    - libgvpr2
    - libjasper1
    - libjpeg8
    - libopenexr22
    - libopenraw1v5
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpathplan4
    - libpng12-0
    - librsvg2-2
    - libsdl2-2.0-0
    - libspiro0
    - libv4l-0
    - libxdot4

  gimp:
    after: [alsa, gegl, desktop-gtk2]
    plugin: autotools
    source: git://git.gnome.org/gimp
    source-tag: 'GIMP_2_8_22'
    configflags:
    - '--prefix=/usr'
    - '--sysconfdir=/etc'
    - '--enable-binreloc'
    install: |
      sed -i 's|^\(.*python=\).*|\1/snap/gimp/current/usr/bin/python|' $SNAPCRAFT_PART_INSTALL/usr/lib/gimp/2.0/interpreters/pygimp.interp
      sed -i 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/gimp.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/gimp.desktop
    build-packages:
    - gettext
    - gnome-pkg-tools
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libaa1-dev
    - libart-2.0-dev
    - libatk1.0-dev
    - libbabl-dev
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexif-dev
    - libfreetype6-dev
    - libfontconfig1-dev
    - libgs-dev
    - libgudev-1.0-dev
    - libice-dev
    - libjasper-dev
    - libjpeg8-dev
    - liblcms2-dev
    - libmng-dev
    - libpng12-dev
    - libpoppler-glib-dev
    - librsvg2-dev
    - libsm-dev
    - libtiff5-dev
    - libwmf-dev
    - libxpm-dev
    - zlib1g-dev
    - patchutils
    - python-dev
    - python-gtk2-dev
    - xsltproc
    stage-packages:
    - libaa1
    - libart-2.0-2
    - libbabl-0.1-0
    - libbz2-1.0
    - libcurl3
    - libexif12
    - libfreetype6
    - libfontconfig1
    - libgs9
    - libgudev-1.0-0
    - libice6
    - libjasper1
    - libjpeg8
    - liblcms2-2
    - libmng2
    - libpng12-0
    - librsvg2-2
    - libsm6
    - libtiff5
    - libwmf0.2-7
    - libxpm4
    - zlib1g
    - python
    - python-dev
    - python-gtk2
